import { User, Event, RSVP, Connection } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Software engineer who loves hiking and good coffee. Always up for outdoor adventures!',
    interests: ['Technology', 'Hiking', 'Coffee', 'Photography'],
    city: 'San Francisco',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-2',
    name: 'Mike Johnson',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Avid reader and book club enthusiast. Let\'s discuss literature over tea!',
    interests: ['Reading', 'Writing', 'Coffee', 'Movies'],
    city: 'San Francisco',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-3',
    name: 'Alex Rivera',
    avatar: 'https://i.pravatar.cc/150?img=13',
    bio: 'Yoga instructor and wellness advocate. Finding peace in movement and mindfulness.',
    interests: ['Yoga', 'Fitness', 'Cooking', 'Music'],
    city: 'Oakland',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-4',
    name: 'Emily Watson',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Artist and creative soul. Love exploring new mediums and meeting fellow creators.',
    interests: ['Art', 'Design', 'Photography', 'Travel'],
    city: 'Berkeley',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-5',
    name: 'David Kim',
    avatar: 'https://i.pravatar.cc/150?img=14',
    bio: 'Foodie and amateur chef. Exploring Bay Area\'s culinary scene one dish at a time.',
    interests: ['Cooking', 'Food & Cooking', 'Travel', 'Photography'],
    city: 'San Francisco',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-6',
    name: 'Lisa Martinez',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Board game enthusiast and community organizer. Let\'s roll some dice!',
    interests: ['Board Games', 'Gaming', 'Technology', 'Coffee'],
    city: 'San Jose',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-7',
    name: 'James Park',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'Musician and guitar teacher. Always looking for jam sessions and live music.',
    interests: ['Music', 'Technology', 'Coffee', 'Movies'],
    city: 'San Francisco',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-8',
    name: 'Rachel Green',
    avatar: 'https://i.pravatar.cc/150?img=10',
    bio: 'Language learner and travel enthusiast. Practicing Spanish and French!',
    interests: ['Language Exchange', 'Travel', 'Reading', 'Coffee'],
    city: 'Oakland',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-9',
    name: 'Tom Anderson',
    avatar: 'https://i.pravatar.cc/150?img=33',
    bio: 'Startup founder and tech geek. Building the future, one line of code at a time.',
    interests: ['Technology', 'Startups', 'Podcasts', 'Fitness'],
    city: 'Palo Alto',
    profileVisibility: 'public',
    showAttendance: true,
  },
  {
    id: 'user-10',
    name: 'Nina Patel',
    avatar: 'https://i.pravatar.cc/150?img=16',
    bio: 'Volunteer coordinator passionate about community service and making a difference.',
    interests: ['Volunteering', 'Yoga', 'Cooking', 'Photography'],
    city: 'San Francisco',
    profileVisibility: 'public',
    showAttendance: true,
  },
];

// Add more users for realistic data
for (let i = 11; i <= 50; i++) {
  mockUsers.push({
    id: `user-${i}`,
    name: `User ${i}`,
    avatar: `https://i.pravatar.cc/150?img=${(i % 70) + 1}`,
    bio: `Enthusiastic community member looking to connect with like-minded people.`,
    interests: [
      ['Reading', 'Technology'],
      ['Hiking', 'Photography'],
      ['Cooking', 'Music'],
      ['Art', 'Design'],
      ['Fitness', 'Yoga'],
    ][i % 5],
    city: ['San Francisco', 'Oakland', 'Berkeley', 'San Jose', 'Palo Alto'][i % 5],
    profileVisibility: 'public',
    showAttendance: i % 3 !== 0,
  });
}

// Mock Events
export const mockEvents: Event[] = [
  {
    id: 'event-1',
    title: 'Morning Hike at Mt. Tamalpais',
    description: 'Join us for a refreshing morning hike at Mt. Tam! We\'ll take the moderate Dipsea Trail and enjoy stunning views of the Bay Area. Perfect for beginners and experienced hikers alike. We\'ll have plenty of breaks for photos and conversation. Bring water, snacks, and sunscreen!',
    category: 'Hiking & Outdoors',
    coverImage: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    hostId: 'user-1',
    locationType: 'in-person',
    address: 'Mt. Tamalpais State Park, Mill Valley, CA',
    city: 'Mill Valley',
    startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    durationMinutes: 180,
    timezone: 'America/Los_Angeles',
    maxCapacity: 15,
    currentAttendees: 12,
    eventStructure: 'structured',
    noiseLevel: 'quiet',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: [
      'What\'s your favorite local hiking trail?',
      'What brought you to the Bay Area?',
      'Have you done any epic hikes recently?',
    ],
    attendeeIds: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'user-8', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14', 'user-15'],
  },
  {
    id: 'event-2',
    title: 'Sci-Fi Book Club: Project Hail Mary',
    description: 'Let\'s discuss Andy Weir\'s brilliant novel Project Hail Mary! We\'ll meet at a cozy cafe to chat about the book\'s themes, characters, and that amazing twist. All opinions welcome - whether you loved it or have critiques. Please finish the book before attending to avoid spoilers!',
    category: 'Book Clubs',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    hostId: 'user-2',
    locationType: 'in-person',
    address: 'Blue Bottle Coffee, Hayes Valley, San Francisco',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
    durationMinutes: 120,
    timezone: 'America/Los_Angeles',
    maxCapacity: 12,
    currentAttendees: 8,
    eventStructure: 'structured',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: [
      'What was your favorite character and why?',
      'What other sci-fi books do you love?',
      'Coffee or tea?',
    ],
    attendeeIds: ['user-2', 'user-4', 'user-8', 'user-16', 'user-17', 'user-18', 'user-19', 'user-20'],
  },
  {
    id: 'event-3',
    title: 'Beginner-Friendly Yoga Flow',
    description: 'Gentle yoga session perfect for beginners or anyone looking to destress. We\'ll focus on basic poses, breathing techniques, and mindfulness. No experience necessary - just bring yourself and an open mind! Mats and props provided.',
    category: 'Fitness',
    coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    hostId: 'user-3',
    locationType: 'in-person',
    address: 'Lake Merritt Park, Oakland, CA',
    city: 'Oakland',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    durationMinutes: 60,
    timezone: 'America/Los_Angeles',
    maxCapacity: 20,
    currentAttendees: 15,
    eventStructure: 'structured',
    noiseLevel: 'quiet',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: [
      'Have you tried yoga before?',
      'What brings you to yoga today?',
      'What\'s your favorite way to relax?',
    ],
    attendeeIds: ['user-3', 'user-10', 'user-21', 'user-22', 'user-23', 'user-24', 'user-25', 'user-26', 'user-27', 'user-28', 'user-29', 'user-30', 'user-31', 'user-32', 'user-33'],
  },
  {
    id: 'event-4',
    title: 'Watercolor Workshop for Beginners',
    description: 'Discover the joy of watercolor painting in this hands-on workshop! We\'ll cover basic techniques, color mixing, and create a simple landscape together. All materials provided. No artistic experience needed - just enthusiasm!',
    category: 'Art & Crafts',
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
    hostId: 'user-4',
    locationType: 'in-person',
    address: 'Berkeley Art Studio, Berkeley, CA',
    city: 'Berkeley',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    durationMinutes: 150,
    timezone: 'America/Los_Angeles',
    maxCapacity: 10,
    currentAttendees: 10,
    eventStructure: 'structured',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: [
      'Have you painted before?',
      'What kind of art do you enjoy?',
      'What inspired you to try watercolors?',
    ],
    attendeeIds: ['user-4', 'user-34', 'user-35', 'user-36', 'user-37', 'user-38', 'user-39', 'user-40', 'user-41', 'user-42'],
  },
  {
    id: 'event-5',
    title: 'Homemade Pasta Night',
    description: 'Learn to make authentic Italian pasta from scratch! We\'ll prepare fresh fettuccine and a delicious sauce, then enjoy our creations together. Bring your appetite and curiosity. Vegetarian and vegan options available.',
    category: 'Food & Cooking',
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
    hostId: 'user-5',
    locationType: 'in-person',
    address: 'Community Kitchen, Mission District, SF',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000), // 4 days from now
    durationMinutes: 180,
    timezone: 'America/Los_Angeles',
    maxCapacity: 12,
    currentAttendees: 9,
    eventStructure: 'mixed',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: [
      'What\'s your favorite pasta dish?',
      'Do you enjoy cooking?',
      'Any dietary restrictions we should know about?',
    ],
    attendeeIds: ['user-5', 'user-43', 'user-44', 'user-45', 'user-46', 'user-47', 'user-48', 'user-49', 'user-50'],
  },
  {
    id: 'event-6',
    title: 'Board Game Night: Strategy Games',
    description: 'Calling all board game enthusiasts! Join us for an evening of strategy games including Catan, Ticket to Ride, and more. We\'ll teach new players and have multiple tables going. Snacks and drinks provided.',
    category: 'Gaming',
    coverImage: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800',
    hostId: 'user-6',
    locationType: 'in-person',
    address: 'GameScape North, San Rafael, CA',
    city: 'San Rafael',
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    durationMinutes: 180,
    timezone: 'America/Los_Angeles',
    maxCapacity: 20,
    currentAttendees: 16,
    eventStructure: 'casual',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: [
      'What\'s your favorite board game?',
      'Are you a competitive player or casual?',
      'Coffee, tea, or board games?',
    ],
    attendeeIds: ['user-6', 'user-11', 'user-12', 'user-13', 'user-14', 'user-15', 'user-16', 'user-17', 'user-18', 'user-19', 'user-20', 'user-21', 'user-22', 'user-23', 'user-24', 'user-25'],
  },
  {
    id: 'event-7',
    title: 'Acoustic Open Mic Night',
    description: 'Share your music or just come listen to local talent! Acoustic guitars, ukuleles, and vocals welcome. Supportive audience guaranteed. Sign-ups start at 7pm, performances at 7:30pm.',
    category: 'Music',
    coverImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    hostId: 'user-7',
    locationType: 'in-person',
    address: 'Red Poppy Art House, SF',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000), // 6 days from now
    durationMinutes: 150,
    timezone: 'America/Los_Angeles',
    maxCapacity: 30,
    currentAttendees: 22,
    eventStructure: 'casual',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: [
      'Do you play an instrument?',
      'Who are your musical influences?',
      'Favorite concert you\'ve been to?',
    ],
    attendeeIds: ['user-7', 'user-26', 'user-27', 'user-28', 'user-29', 'user-30', 'user-31', 'user-32', 'user-33', 'user-34', 'user-35', 'user-36', 'user-37', 'user-38', 'user-39', 'user-40', 'user-41', 'user-42', 'user-43', 'user-44', 'user-45', 'user-46'],
  },
  {
    id: 'event-8',
    title: 'Spanish Conversation Practice',
    description: 'Practice your Spanish in a relaxed, judgment-free environment! All levels welcome from beginner to advanced. We\'ll have conversation prompts and games to keep things fun and engaging.',
    category: 'Language Exchange',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800',
    hostId: 'user-8',
    locationType: 'virtual',
    virtualLink: 'https://zoom.us/j/mock-meeting',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    durationMinutes: 90,
    timezone: 'America/Los_Angeles',
    maxCapacity: 15,
    currentAttendees: 11,
    eventStructure: 'structured',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: [
      '¿De dónde eres? (Where are you from?)',
      '¿Por qué estudias español? (Why are you learning Spanish?)',
      '¿Cuál es tu comida favorita? (What\'s your favorite food?)',
    ],
    attendeeIds: ['user-8', 'user-47', 'user-48', 'user-49', 'user-50', 'user-11', 'user-12', 'user-13', 'user-14', 'user-15', 'user-16'],
  },
  {
    id: 'event-9',
    title: 'Tech Talk: Intro to AI & Machine Learning',
    description: 'Curious about AI but don\'t know where to start? Join our beginner-friendly tech talk! We\'ll demystify AI concepts and discuss real-world applications. Q&A included. No coding experience required.',
    category: 'Tech Meetups',
    coverImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    hostId: 'user-9',
    locationType: 'virtual',
    virtualLink: 'https://zoom.us/j/mock-meeting-2',
    startDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000), // 8 days from now
    durationMinutes: 90,
    timezone: 'America/Los_Angeles',
    maxCapacity: 50,
    currentAttendees: 38,
    eventStructure: 'structured',
    noiseLevel: 'quiet',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: [
      'What interests you about AI?',
      'What tech field do you work in?',
      'Have you used any AI tools?',
    ],
    attendeeIds: Array.from({ length: 38 }, (_, i) => `user-${i + 1}`),
  },
  {
    id: 'event-10',
    title: 'Beach Cleanup & Picnic',
    description: 'Make a difference while meeting great people! We\'ll spend the morning cleaning Ocean Beach, then enjoy a potluck picnic. Gloves and bags provided. Bring a dish to share if you can!',
    category: 'Volunteering',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    hostId: 'user-10',
    locationType: 'in-person',
    address: 'Ocean Beach, San Francisco, CA',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000), // 9 days from now
    durationMinutes: 180,
    timezone: 'America/Los_Angeles',
    maxCapacity: 25,
    currentAttendees: 18,
    eventStructure: 'mixed',
    noiseLevel: 'moderate',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: [
      'What brings you to volunteer today?',
      'Favorite beach in the Bay Area?',
      'What dish are you bringing to the picnic?',
    ],
    attendeeIds: ['user-10', 'user-1', 'user-3', 'user-17', 'user-18', 'user-19', 'user-20', 'user-21', 'user-22', 'user-23', 'user-24', 'user-25', 'user-26', 'user-27', 'user-28', 'user-29', 'user-30', 'user-31'],
  },
];

// Add more events for variety
const additionalEvents: Event[] = [
  {
    id: 'event-11',
    title: 'Photography Walk: Golden Hour',
    description: 'Capture stunning golden hour shots around the Embarcadero! All camera types welcome including smartphones. We\'ll share tips and techniques.',
    category: 'Hiking & Outdoors',
    coverImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
    hostId: 'user-1',
    locationType: 'in-person',
    address: 'Ferry Building, SF',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    durationMinutes: 120,
    timezone: 'America/Los_Angeles',
    maxCapacity: 15,
    currentAttendees: 7,
    eventStructure: 'casual',
    noiseLevel: 'quiet',
    newcomerFriendly: true,
    isRecurring: false,
    iceBreakers: ['What camera do you use?', 'Favorite subject to photograph?'],
    attendeeIds: ['user-1', 'user-4', 'user-32', 'user-33', 'user-34', 'user-35', 'user-36'],
  },
  {
    id: 'event-12',
    title: 'Startup Networking Mixer',
    description: 'Connect with fellow entrepreneurs and startup enthusiasts! Casual networking with optional 1-minute pitches.',
    category: 'Tech Meetups',
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
    hostId: 'user-9',
    locationType: 'in-person',
    address: 'WeWork SoMa, SF',
    city: 'San Francisco',
    startDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
    durationMinutes: 120,
    timezone: 'America/Los_Angeles',
    maxCapacity: 40,
    currentAttendees: 35,
    eventStructure: 'casual',
    noiseLevel: 'lively',
    newcomerFriendly: true,
    isRecurring: true,
    iceBreakers: ['What are you working on?', 'Looking for cofounders?'],
    attendeeIds: Array.from({ length: 35 }, (_, i) => `user-${(i % 50) + 1}`),
  },
];

mockEvents.push(...additionalEvents);

// Mock RSVPs
export const mockRSVPs: RSVP[] = mockEvents.flatMap((event) =>
  event.attendeeIds.map((userId) => ({
    userId,
    eventId: event.id,
    status: 'going' as const,
    createdAt: new Date(event.startDate.getTime() - Math.random() * 10 * 24 * 60 * 60 * 1000),
  }))
);

// Mock Connections
export const mockConnections: Connection[] = [
  { userAId: 'user-1', userBId: 'user-2', eventsAttendedTogether: 3, firstEventId: 'event-1' },
  { userAId: 'user-1', userBId: 'user-3', eventsAttendedTogether: 2, firstEventId: 'event-1' },
  { userAId: 'user-1', userBId: 'user-10', eventsAttendedTogether: 4, firstEventId: 'event-10' },
  { userAId: 'user-2', userBId: 'user-4', eventsAttendedTogether: 2, firstEventId: 'event-2' },
  { userAId: 'user-2', userBId: 'user-8', eventsAttendedTogether: 1, firstEventId: 'event-2' },
  { userAId: 'user-3', userBId: 'user-10', eventsAttendedTogether: 5, firstEventId: 'event-3' },
  { userAId: 'user-5', userBId: 'user-6', eventsAttendedTogether: 2, firstEventId: 'event-5' },
  { userAId: 'user-6', userBId: 'user-7', eventsAttendedTogether: 3, firstEventId: 'event-6' },
];

// Current logged-in user (for demo purposes)
export const currentUser: User = mockUsers[0]; // Sarah Chen
